name: tests

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Composer dependencies
        run: composer install

      - name: PHPUnit Tests
        run: vendor/bin/phpunit
