name: tests

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [7.2, 7.3, 7.4, 8.0]

    steps:
      - uses: actions/checkout@v2

      - name: Install Composer dependencies
        run: composer install

      - name: PHPUnit Tests
        run: vendor/bin/phpunit
