name: Test

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@2

      - name: PHPUnit Tests
        uses: php-actions/phpunit@9
        with:
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          args: --coverage-text
